language: cpp
sudo: required
dist: trusty
compiler:
- clang
- gcc
os:
- linux
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
before_install:
- eval "${MATRIX_EVAL}"
- sudo apt-get install build-essential autoconf automake cmake libboost-all-dev libconfig++-dev
- wget https://nih.at/libzip/libzip-0.11.2.tar.gz
- tar xvfp libzip-0.11.2.tar.gz
- pushd libzip-0.11.2 && ./configure --prefix=/usr && make && sudo make install
- popd
- git clone https://github.com/emweb/wt.git wt
- pushd wt;
- git checkout 4.0.3
- cmake -DCMAKE_INSTALL_PREFIX=/usr && sudo make install
- popd
script: autoreconf -vfi && ./configure && make
env:
  global:
    - MAKEFLAGS="-j 2"
